### ISSUE TITLE
Graphical Output should take less space

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/visualisation#1]
The graphical output generates much space with (header and navigation), and also
the free space between components is too large (see bumperbot to sensors) to use it inside the onlineIDE.
The components are also too wide and too heigh (see sensors is too wide) for use inside onlineIDE.
Maybe text of input ports is left below and text of output ports is right above the port squares, so that the component width can be decreased.
In the bumperbot example the components are also too heigh, a third of the height would be enough, and the vertical space is also kind of too large.

<img width="1269" alt="bildschirmfoto 2017-11-22 um 00 46 48" src="https://user-images.githubusercontent.com/30497492/33102786-bb643132-cf1e-11e7-8506-ddcf269f3bd2.png">

**Comment by vonwenckstern** [comment]
maybe the cmd tool has an additional option `--compress` to compress the size; otherwise you can use it as it is

so it can be used for two different cases:
- one for the online IDE (see screenshot)
- one for the documentation (without online IDE)

**Comment by ManuelSchrick** [comment]
I'm not sure this is the right way to approach that problem. First: All components have the same width. I cannot change the width of single components. That wouldn't help because there might be other components in the same column that need the whole width of the column because e.g. they have input as well as output ports.
The distance between the ports are intentionally of this size because port names tend to get very long and there will often be line breaks within the name. Reducing the distance will cause port names to overlap. And if we put, as you proposed, the names of output ports right above and the ones of input ports left below the port itself (if I  got it right, they'll be outside of the component), the problem would just get moved to another place. Then the output port name of one connection would overlap with the input port name of the connection above.
Also: There will always be models that are too big for the visualization tab. Especially real live examples like FAS will not fit into the small tab with the port names showing and being big enough to read.
I would suggest implementing a zoom functionality into the IDE so one could zoom out to see the whole picture or zoom in to read port names etc.

**Comment by vonwenckstern** [comment]
Yeah, I understand that the FAS is too large. But the hope was that we get better spacing for smaller examples such as the bumperbot. (And the spacing above and below the navigation bar can be easily reduced).

And maybe there is an easy solution of pre-calculating the width for of the components for each layer. We can count the the length of letters of port names after the layout for the components for the columns and rows have been done. Then we can adopt the the spacing the SVG output without touching the layout algorithm.
Then we also can reduce the sizing when we do not show the port names (since then there length is zero), so we get more out of the three zooming options.

We can discuss it during the next meeting - you probably have better ideas which are not to hard to implement to squeeze the boxes more together. (But we do not want to change your layout algorithm too much, just adapt the constants for spacing)
