### ISSUE TITLE
What option need I declare to generate all 3 view kinds in the SVG output file?

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/visualisation#2]
You showed me that you can generate a menu inside the HTML file to switch between the three different view detail modes.
How can I generate it?
Could you please do it for the bumperbot example and replace the content of the `.c9/svg` folder?
https://github.com/EmbeddedMontiArc/Demos/blob/master/bumperbot.zip

**Comment by ManuelSchrick** [comment]
The three detail modes we added, were added to the algorithm that was implemented by the other students during the practical course. It has not been adapted to the new (path-based) algorithm yet. What does work is the "normal" mode and the "no port names" mode. But the "simplified" mode has to be implemented into the new algorithm.
That's why the drop down menu doesn't show.

**Comment by ManuelSchrick** [comment]
I spent today implementing the "simplified" mode into the new algorithm. The current code version will create all three versions with the drop-down menu in the top left corner.

**Comment by vonwenckstern** [comment]
Thank you, so we see now the advantage of automatically layouting.

But the sizes can be optimized:
In https://embeddedmontiarc.github.io/visualisation/svg/BumperBot/testManuelSchrick.bumperBot_no_port_names.html
which shows no port names the layout takes nearly as much space as the one with port names (see #1).
